### PR TITLE
Add logs to CentralConfig 3xx and 4xx responses.

### PR DESCRIPTION
**Pull request by linjunpop**
So the client will have logs on why Central Config fails.

### CODE REVIEW

**Comment by astorm** [comment]
Thanks for the PR @linjunpop! It looks like the continuous integration system isn't happy about something.  You should be able to run this locally via `npm`

```
$ npm run test
```

and then make any changes necessary to fix tests and/or make the linter happy. 

Once the tests are green we'll give this one a review.

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by linjunpop** [comment]
Hi @astorm ,

Looks like all tests have passed, would you plz review? Thanks.

**Comment by trentm** [comment]
@linjunpop Thank you very much for this PR. I am sorry we did not respond in a timely manner. In https://github.com/elastic/apm-agent-nodejs/pull/3507 we moved the APM http-client (this repo) to the APM agent repo at https://github.com/elastic/apm-agent-nodejs. I've adapted your patch to a new PR at https://github.com/elastic/apm-agent-nodejs/pull/3549

**Comment by linjunpop** [comment]
Thank you @trentm

**Pull request closed without merging**
